"""empty message

Revision ID: 022815a8a401
Revises: 9fee043a294d
Create Date: 2022-12-26 00:22:20.175663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022815a8a401'
down_revision = '9fee043a294d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_Name', sa.String(length=255), nullable=False),
    sa.Column('last_Name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('apartment_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'borrowers', ['borrower_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('borrower_id')

    op.drop_table('borrowers')
    # ### end Alembic commands ###
