"""empty message

Revision ID: 4fb87221e5ab
Revises: 022815a8a401
Create Date: 2022-12-26 21:26:31.458230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fb87221e5ab'
down_revision = '022815a8a401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_Name', sa.String(length=255), nullable=False),
    sa.Column('last_Name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('apartment_number', sa.String(), nullable=False),
    sa.Column('late_returns', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('borrowers')
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_constraint('borrow_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'borrower', ['borrower_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('borrow_ibfk_2', 'borrowers', ['borrower_id'], ['id'])

    op.create_table('borrowers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_Name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_Name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('apartment_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('borrower')
    # ### end Alembic commands ###
