"""empty message

Revision ID: 7749dd979df2
Revises: 7e6003249ded
Create Date: 2023-01-17 09:53:23.351164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7749dd979df2'
down_revision = '7e6003249ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
