"""empty message

Revision ID: 9e4f81bd9b57
Revises: 0dbc649dfee4
Create Date: 2023-01-13 11:09:20.111482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e4f81bd9b57'
down_revision = '0dbc649dfee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrower', schema=None) as batch_op:
        batch_op.drop_column('apartment_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apartment_number', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
