"""empty message

Revision ID: 9fee043a294d
Revises: bd739b3fdbff
Create Date: 2022-12-20 15:19:33.063033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fee043a294d'
down_revision = 'bd739b3fdbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
