"""empty message

Revision ID: cc05a10449c2
Revises: 6fab515615cd
Create Date: 2022-12-29 22:05:56.427732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc05a10449c2'
down_revision = '6fab515615cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('overdue', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('daysleft', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_column('daysleft')
        batch_op.drop_column('overdue')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
