"""empty message

Revision ID: d1d676a1d3e1
Revises: eeccc1084c92
Create Date: 2022-12-26 22:01:13.828013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1d676a1d3e1'
down_revision = 'eeccc1084c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=False))
        batch_op.drop_column('first_Name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_Name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
