"""empty message

Revision ID: e58ac2934ec2
Revises: 9e4f81bd9b57
Create Date: 2023-01-13 13:15:12.856558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e58ac2934ec2'
down_revision = '9e4f81bd9b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrower', schema=None) as batch_op:
        batch_op.drop_column('superuser')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
