"""empty message

Revision ID: e7fb41cc76a0
Revises: e92564adbf5e
Create Date: 2023-01-12 15:41:57.489015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7fb41cc76a0'
down_revision = 'e92564adbf5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superuser', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('borrower', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('superuser')

    # ### end Alembic commands ###
